# Generated by Django 4.2 on 2024-02-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='stripe_id'),
        ),
    ]
