# Generated by Django 4.2 on 2024-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_id',
            field=models.CharField(blank=True, null=True, verbose_name='stripe_id'),
        ),
    ]
